#!/usr/bin/env bash
# This script is displaying information about school file
file_h="school"

if [ -e "$file_h" ]
then

    echo "school file exists"
    if [ -s "$file_h" ]
    then
        echo "school file does not exist"
    else
        echo "school file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi